
FROM codingforentrepreneurs/python:3.9-webapp-cassandra
COPY .env /proj/.env
COPY ./app /proj/app
COPY ./requirements.txt /proj/requirements.txt
COPY ./entrypoint.sh /proj/entrypoint.sh
WORKDIR /proj

RUN python3 -m venv /opt/venv && /opt/venv/bin/python -m pip install -r requirements.txt

CMD [ "entrypoint.sh" ]